### PR TITLE
[#11,#15,#16,#17] get project building against master again (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #11, #15, #16, and #17.

Regarding the fix for #15 here:
Going off my previous discussion with @trel where we decided not to include `InstallDirs.cmake` in every project, we may wish to move macros like `IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH` into a cmake file included in `irods-dev`.
(If we decide to do this, I feel it is out of scope for this particular pull request and should be addressed separately)

### CODE REVIEW

**Comment by trel** [comment]
I would say, yes, in general, anything we can create a single source of truth for... we should.   We have a great number of moving parts - and if they could all derive their brain from the same place, that's great.   Also, a separate work unit, definitely.

**Comment by trel** [comment]
so the openssl was strictly copy/paste?    hmmm.

**Comment by SwooshyCueb** [comment]
Looks that way. We're not linking against it, and I didn't see any includes.

**Comment by trel** [comment]
carry on.   happy to see them #'d.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
